export const USER_CHANGED = 'user_changed';
export const USER_LOADING_CHANGED = 'user_loading_changed';
export const ACCOUNT_CHANGED = 'account_changed';
export const CONTENT_CHANGED = 'content_changed';

export const USER = {
  TOKEN_FETCHED: 'TOKEN_FETCHED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export const GENERIC_ACTIONS = {
  SHOW_HIDE_LOADING_ERROR_MESSAGE: 'SHOW_HIDE_LOADING_ERROR_MESSAGE',
};
export const DASHBOARD = {
  GET_DASHBOARD: 'GET_DASHBOARD',
  DASHBOARD_CHANGED: 'DASHBOARD_CHANGED',
};

export const TEACHERS = {
  GET_TEACHERS: 'GET_TEACHERS',
  ADD_TEACHER: 'ADD_TEACHER',
  SET_TEACHER: 'SET_TEACHER',
  DELETE_TEACHER: 'DELETE_TEACHER',
};
export const CLASSES = {
  GET_CLASS_TEACHERS: 'GET_CLASS_TEACHERS',
  GET_CLASSES: 'GET_CLASSES',
  ADD_CLASS: 'ADD_CLASS',
  CLASS_TIME_LOG: 'CLASS_TIME_LOG',
  CLASS_LOADING_CHANGED: 'CLASS_LOADING_CHANGED',
  CLASS_DELETE_SUCCESS: 'CLASS_DELETE_SUCCESS',
  CLASS_MISSING_LOG: 'CLASS_MISSING_LOG',
  CLASS_SELECT: 'CLASS_SELECT',
  CLASS_FORM_CHANGE: 'CLASS_FORM_CHANGE',
  CLASS_FORM_RESET: 'CLASS_FORM_RESET',
  CLASS_DELETED_SUCCESS: 'CLASS_DELETED_SUCCESS',
};
